Month7/step 2
edgar-ianke/react-stellar-burger pull request #2
Opened 2023-09-07 08:13 UTC by edgar-ianke

2023-09-07 10:10 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **очень хорошую** работу на старте вашего проекта, вёрстка корректная и аккуратная, код лаконичный и не содержит лишнего, использованы функциональные компоненты, **так держать** 👍

Тем не менее, для успешной сдачи работы на данном этапе вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Для некоторых компонент следует дополнить их PropTypes;
- У ModalOverlay не должно быть children, это просто компонент подложки а не контейнер;
- Обработчик закрытия попапа должен добавляться при открытии попапа и удаляться при закрытии;
- Согласно дизайну ширина заголовка не должна растягиваться на всю ширину экрана, а соответствует ширине контейнера снизу;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:


- Распространенной практикой именования файлов в проекте является стиль `kebab-case`, где не используются заглавные буквы, а разделение слов в названии производится за счет тире. Это позволяет избежать ошибок, когда в регистро-независимых файловых системах проект собирается, а на других нет. a

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления комментариев выше и указанных в коде с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-09-07 10:10 UTC, randomroot commented on src/utils/Api.js
> +const url = "https://norma.nomoreparties.space/api/ingredients";
🟡 **Можно улучшить:**

В данном случае имеет смысл вынести базовый урл `https://norma.nomoreparties.space/api` в константу, а уже внутри класса Api создать метод, который получает список ингредиентов, дополняя урл выше `${API_URL}/ingredients`

2023-09-07 10:10 UTC, randomroot commented on src/utils/Api.js
> +  _checkResponse(res) {
🟢 **Отлично:**

Хорошо, что вынесли проверку сразу в отдельную функцию, в дальнейшем её переиспользование будет удобнее

2023-09-07 10:10 UTC, randomroot commented on src/components/order-details/order-details.module.css
> +  composes: text text_type_digits-large pt-30 pb-8 from global;
🟢 **Отлично:**

Использование современных подходов 👍

2023-09-07 10:10 UTC, randomroot commented on src/components/order-details/order-details.jsx
> +export default function OrderDetails(props) {
🔴 **Нужно исправить:**

Для данного компонента следует указать его `PropTypes`

2023-09-07 10:10 UTC, randomroot commented on src/components/modal-overlay/modal-overlay.jsx
> +export default function ModalOverlay(props) {
🔴 **Нужно исправить:**

У ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-09-07 10:10 UTC, randomroot commented on src/components/modal-overlay/modal-overlay.jsx
> +  }, []);
🔴 **Нужно исправить:**

Обработчик закрытия попапа должен добавляться при открытии попапа и удаляться при закрытии. Сейчас обработчик не будет удаляться при закрытии попапа т.к. из хука useEffect нужно возвращать колбэк отписки. Должно быть примерно так:

```jsx
   useEffect(() => {
      const handleESCclose = () => {............} //обработчик события
      document.addEventListener("keydown", handleESCclose); //навешиваем обработчик
	  
	  //возвращаем колбэк отписки, который  будет вызван при размонтировании компонента
      return () => document.removeEventListener("keydown", handleESCclose)                                                                                               
   }, [onClose])
```

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [activeTab, setactiveTab] = React.useState(tabBar[0].name);
🔴 **Нужно исправить:**

Переменные следует привести к виду `camelCase`

🟡 **Можно улучшить:**

В стейте имеет смысл хранить именно "тип", вместо названия

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +              <Tab key={i + 1} value={el.name} active={activeTab === el.name} onClick={handleClick}>
🟡 **Можно улучшить:**

В качестве ключа целесообразно использовать уникальное значение "тип"

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  data: PropTypes.arrayOf(ingredientPropType).isRequired,
🟡 **Можно улучшить:**

В типизации элементы массива следует указывать также как обязательные, если в массиве не ожидаются пустые значения:

```PropTypes.arrayOf(elementType.isRequired).isRequired```

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  const bun = props.data.filter((item) => item.type === "bun")[0];
🟡 **Можно улучшить:**

В данном случае лучше использовать функцию `find` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find), чтобы не генерировать дополнительный массив

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  const totalPrice = bun.price + cart.reduce((acc, currVal) => acc + currVal, 0);
🔴 **Нужно исправить:**

Цену булки следует удваивать, т.к. в заказе их присутствует две - одна сверху, а другая снизу

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                <li key={i} className={burgerConsturctorStyles.ingr}>
🟡 **Можно улучшить:**

В качестве ключа в перспективе лучше не использовать индекс, т.к. это приведет к дополнительным ре-рендерам, когда список станет редактируемым, предпочтительно использовать уникальным и неизменяемый ключ (например `id` или генерируемый через UUID единоразово)

2023-09-07 10:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +export default function BurgerConsturctor(props) {
🟡 **Можно улучшить:**

Небольшая орфографическая ошибка в названии

2023-09-07 10:10 UTC, randomroot commented on src/components/app/app.jsx
> +    state.isLoading === false && (
🟡 **Можно улучшить:**

Можно сделать код лаконичнее, если вынести условие в отдельный `if`: 

```jsx
if (state.isLoading) {
  return null;
}

return (
  <App ... />
);
```

2023-09-07 10:10 UTC, randomroot commented on src/components/app/app.jsx
> +        console.log(err);
🟡 **Можно улучшить:**

В случае возникновения ошибки имеет смысл вывести пользователю сообщение, чтобы он не пугался пустого экрана :)

2023-09-07 10:10 UTC, randomroot commented on src/components/ingredients-section/ingredients-section.jsx
> +        {props.type.map((tab, ind) => {
🟡 **Можно улучшить:**

1) Для оптимизации рендеринга целесообразно вынести фильтрацию по типу в отдельные переменные, а внизу уже работать с готовыми наборами данных
2) Категорию ингредиентов можно вынести в отдельный компонент

2023-09-07 10:10 UTC, randomroot commented on src/components/ingredients-section/ingredients-section.jsx
> +  type: PropTypes.arrayOf(
🟡 **Можно улучшить:**

Пропс рекомендуется сделать обязательным

2023-09-11 07:40 UTC, edgar-ianke commented on src/components/order-details/order-details.jsx
> +export default function OrderDetails(props) {
Исправлено

2023-09-11 07:40 UTC, edgar-ianke commented on src/components/modal-overlay/modal-overlay.jsx
> +export default function ModalOverlay(props) {
Исправлено

2023-09-11 07:40 UTC, edgar-ianke commented on src/components/modal-overlay/modal-overlay.jsx
> +  }, []);
Исправлено

2023-09-11 07:40 UTC, edgar-ianke commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [activeTab, setactiveTab] = React.useState(tabBar[0].name);
Исправлено

2023-09-11 07:41 UTC, edgar-ianke commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  data: PropTypes.arrayOf(ingredientPropType).isRequired,
Исправлено

2023-09-11 07:41 UTC, edgar-ianke commented on src/components/burger-constructor/burger-constructor.jsx
> +  const totalPrice = bun.price + cart.reduce((acc, currVal) => acc + currVal, 0);
Исправлено

2023-09-11 10:46 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- В ModalOverlay было исключено только описание пропса `children`, но в коде внутрь него передаются элементы по прежнему. Разместите его рядом с другими элементами модального окна, вместо передачи их внутрь оверлея: `<Modal><ModalOverlay /><div> ... </div></Modal>`

**Хорошего вам дня и настроения!** 🐈

2023-09-13 08:13 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-10-02 07:17 UTC, merged